name: Branch Protection

on:
  pull_request:
    branches: [ main, dev ]
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  check-branch-flow:
    runs-on: ubuntu-latest
    name: check-branch-flow
    
    steps:
    - name: Check branch flow rules
      run: |
        echo "Source branch: ${{ github.head_ref }}"
        echo "Target branch: ${{ github.base_ref }}"
        
        # Rule 1: Only dev branch can merge to main
        if [ "${{ github.base_ref }}" == "main" ] && [ "${{ github.head_ref }}" != "dev" ]; then
          echo "❌ ERROR: Pull requests to 'main' branch are only allowed from 'dev' branch."
          echo "Current attempt: ${{ github.head_ref }} → main"
          echo "Required flow: feature → dev → main"
          exit 1
        fi
        
        # Rule 2: Prevent main from merging to dev (reverse flow)
        if [ "${{ github.base_ref }}" == "dev" ] && [ "${{ github.head_ref }}" == "main" ]; then
          echo "❌ ERROR: Pull requests from 'main' to 'dev' are not allowed."
          echo "This would create a reverse flow. Use proper branching: feature → dev → main"
          exit 1
        fi
        
        # Success cases
        if [ "${{ github.base_ref }}" == "main" ] && [ "${{ github.head_ref }}" == "dev" ]; then
          echo "✅ VALID: dev → main (release flow)"
        elif [ "${{ github.base_ref }}" == "dev" ]; then
          echo "✅ VALID: ${{ github.head_ref }} → dev (feature flow)"
        else
          echo "✅ VALID: ${{ github.head_ref }} → ${{ github.base_ref }}"
        fi
        
        echo "Branch flow validation passed!"